services:
  dbprod:
    networks:
      - new
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod

  django-web:
    image: todo-app-image
    container_name: django-docker
    depends_on:
      - dbprod
    networks:
      - new
    volumes:
      - ./static:/app/staticfiles
    env_file:
      - .env.prod

  frontend-proxy:
    image: nginx:latest
    ports:
      - "8001:80"
    networks:
      - new
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
    depends_on:
      - django-web
volumes:
  postgres_data:

networks:
  new:
  legacy: